### ISSUE TITLE
External Tool Failure

### ISSUE THREAD

**Issue by muhdtalha** [mikaeldeity/AutoSync#3]
Revit unable to run the external application "Autosync". Can you please guide if I am doing anything wrong?
![Screenshot 2023-04-05 081532](https://user-images.githubusercontent.com/129921300/229972566-77fb199a-b006-4c1c-8410-3986e115740c.png)

**Comment by mikaeldeity** [comment]
Try unblocking the assembly.

Example here:

![image](https://user-images.githubusercontent.com/22296105/233948955-67460a7f-ea67-4595-91b6-e2c054832c82.png)
