### ISSUE TITLE
FileLoadException error with plugin

### ISSUE THREAD

**Issue by dronov-dmitry** [mikaeldeity/AutoSync#5]
We have some error with plugin
Can you help pls what it can be?
We put plugin in %appdata%\Autodesk\Revit\Addins\2022
![image](https://github.com/mikaeldeity/AutoSync/assets/9892891/d33e1ee5-e91f-4d8f-a818-2b094314d9ab)

**Comment by dronov-dmitry** [comment]
We fix this problem with unblock file
Thx a lot for plugin
![image](https://github.com/mikaeldeity/AutoSync/assets/9892891/f54c796d-5956-45e9-9fd6-e7378023a6ae)
![image](https://github.com/mikaeldeity/AutoSync/assets/9892891/09108578-8e0d-4c97-a4c3-e1953909b379)

**Comment by mikaeldeity** [comment]
@dronov-dmitry glad you solved! This is a common issue for internet downloaded files.
